"""Fetch the webfonts this site uses and store them locally in fonts/.

Replaces the Google Fonts CDN <link> with self-hosted .woff2 files, which is
what the PRD asked for. Every face is pulled as the latin subset only -- the
unicode-range in Google's own CSS is what keeps the request small, and the
site is English/Indonesian throughout, so latin covers it.

The @font-face block that design-system.css already declares is written by this
script too, so the CSS and the files on disk can never drift apart. Re-running
the script is safe and idempotent.
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "fonts")
CSS_OUT = os.path.join(ROOT, "css", "fonts.css")

# A modern desktop UA is required: Google serves woff2 only to browsers it
# recognises, and falls back to ttf for anything it does not know.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# family -> (css2 query fragment, weights to keep)
FAMILIES = [
    ("Press Start 2P", "Press+Start+2P", [400]),
    ("Silkscreen", "Silkscreen:wght@400;700", [400, 700]),
    ("IBM Plex Mono", "IBM+Plex+Mono:wght@400;500;600;700", [400, 500, 600, 700]),
]

# Only the plain latin range. Google emits one @font-face per subset
# (latin, latin-ext, cyrillic, vietnamese...), which is ~6 files per weight.
# We want exactly one.
LATIN_RANGE = "U+0000-00FF, U+0131, U+0152-0153"


def fetch(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def parse_css(css):
    """Yield (family, weight, style, woff2_url) for latin faces only."""
    out = []
    for block in re.findall(r"@font-face\s*\{(.*?)\}", css, re.S):
        def field(name):
            m = re.search(name + r"\s*:\s*([^;]+);", block)
            return m.group(1).strip() if m else ""

        urange = field("unicode-range")
        src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        if not src:
            continue
        # Keep the latin block only: it is the one that starts at U+0000-00FF.
        if urange and not urange.startswith("U+0000-00FF"):
            continue
        family = field("font-family").strip().strip("\"'")
        out.append((family, field("font-weight") or "400", field("font-style") or "normal", src.group(1)))
    return out


def slug(family):
    return re.sub(r"[^a-z0-9]+", "-", family.lower()).strip("-")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)

    query = "&".join("family=" + q for _, q, _ in FAMILIES)
    url = "https://fonts.googleapis.com/css2?%s&display=swap" % query
    print("fetching stylesheet: %s" % url)
    try:
        css = fetch(url).decode("utf-8")
    except Exception as exc:
        print("FAILED to fetch stylesheet: %s" % exc)
        return 1

    faces = parse_css(css)
    if not faces:
        print("FAILED: no latin @font-face rules found -- aborting, "
              "refusing to write a stylesheet that would break the site")
        return 1

    blocks, total = [], 0
    for family, weight, style, woff2 in faces:
        name = "%s-%s.woff2" % (slug(family), weight)
        if style != "normal":
            name = "%s-%s-%s.woff2" % (slug(family), weight, style)
        dest = os.path.join(FONT_DIR, name)

        if os.path.exists(dest) and os.path.getsize(dest) > 0:
            size = os.path.getsize(dest)
            print("  cached  %-28s %6d bytes" % (name, size))
        else:
            try:
                data = fetch(woff2)
            except Exception as exc:
                print("  FAILED  %-28s %s" % (name, exc))
                return 1
            if data[:4] != b"wOF2":
                print("  FAILED  %-28s not a woff2 file" % name)
                return 1
            with open(dest, "wb") as fh:
                fh.write(data)
            size = len(data)
            print("  saved   %-28s %6d bytes" % (name, size))
        total += size

        blocks.append(
            "@font-face {\n"
            '  font-family: "%s";\n'
            '  src: url("../fonts/%s") format("woff2");\n'
            "  font-weight: %s;\n"
            "  font-style: %s;\n"
            "  font-display: swap;\n"
            "}" % (family, name, weight, style)
        )

    header = (
        "/* ==========================================================================\n"
        "   fonts.css -- self-hosted webfonts\n"
        "   ==========================================================================\n"
        "   GENERATED by tools/fetch_fonts.py -- do not edit by hand.\n"
        "\n"
        "   Latin subset only; the site is English/Indonesian. Every file here is\n"
        "   an official Google Fonts build served from fonts/, so the page has no\n"
        "   third-party dependency and no render-blocking request to fonts.gstatic\n"
        "   .com. Loaded before design-system.css so --font-* tokens resolve.\n"
        "   ========================================================================== */\n\n"
    )
    with open(CSS_OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header + "\n\n".join(blocks) + "\n")

    print("\n%d faces, %d bytes (%.1f KB) total" % (len(faces), total, total / 1024))
    print("wrote %s" % CSS_OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
